#!/bin/bash
# prompt color according to exit value
# Displays also the temperature of a Raspi
#

Setup()
{

	RED="$(tput setaf 1)"
 	GREEN="$(tput setaf 2)"
	YELLOW="$(tput  setaf 3)"
	BLUE="$(tput  setaf 4)"
  	MAGENTA="$(tput  setaf 5)"
  	CYAN="$(tput  setaf 6)"
  	WHITE="$(tput  setaf 7)"
  	RESET="$(tput  setaf 9)$(tput sgr0)"
  
}

FPromptCmd()
{

	#
	# save the last rc
	#
	export RET=$?
	[ "$RET" == "0" ] && post="" || post="[$RET]"
	#
	# calculate the CPU temperature
	#
 	t=$(($(cat /sys/class/thermal/thermal_zone*/temp)/1000))
	#
	# change color of username to $RED if we're root 
	#
	[ $(id -u) == 0 ] && { 
		UCOL=$RED 
		PR="_#"}||{
		UCOL=$WHITE
		PR="_:"}
		
	#

} 

Setup
export PROMPT_COMMAND=FPromptCmd
PS1="(\$t)\[$INV\]\[\$UCOL\]\u@\h\[$NORMAL\]\[$CYAN\]"
PS1+="\[$GREEN\]"
PS1+="\w"
PS1+="\[$RED\]\${post}\[$GREEN\]\$PR"
PS1+="\[$WHITE\]"
export PS1


