#!/bin/bash
# prompt color according to exit value
# Displays also the temperature of a Raspi
#

Setup()
{
	RED=$(tput setaf 1)
 	GREEN=$(tput setaf 2)
	YELLOW=$(tput  setaf 3)
	BLUE=$(tput  setaf 4)
  	MAGENTA=$(tput  setaf 5)
  	CYAN=$(tput  setaf 6)
  	WHITE=$(tput  setaf 7)
  	RESET=$(tput  setaf 9)
  
  	HOSTNAME=$(hostname)

}

FPromptCmd()
{
	RET=$?
 	t=$(($(cat /sys/class/thermal/thermal_zone*/temp)/1000))
	
	pre="${UCOL}[$USER@$HOSTNAME]$CYAN($t)$GREEN$PWD"
	[ $RET == 0 ]  || pre=${pre}${RED}[${RET}]
} 


Setup
PROMPT_COMMAND=FPromptCmd

PS1="${pre}_:${WHITE}"
