#!/bin/bash
# prompt color according to exit value
# Displays also the temperature of a Raspi
#

Setup()
{
	RED="\001$(tput setaf 1)\002"
 	GREEN="\001$(tput setaf 2)\002"
	YELLOW="\001$(tput  setaf 3)\002"
	BLUE="\001$(tput  setaf 4)\002"
  	MAGENTA="\001$(tput  setaf 5)\002"
  	CYAN="\001$(tput  setaf 6)\002"
  	WHITE="\001$(tput  setaf 7)\002"
  	RESET="\001$(tput  setaf 9)\002""\001$(tput sgr0)\002"

  
  	HOSTNAME=$(hostname)

}

FPromptCmd()
{

	#
	# save the last rc
	#
	RET=$?
	#
	# calculate the CPU temperature
	#
 	t=$(($(cat /sys/class/thermal/thermal_zone*/temp)/1000))
	#
	# change color of username to $RED if we're root 
	#
	[ $(id -u) == 0 ] && UCOL=$RED || UCOL=$WHITE
	#
	# Build the prefix of the prompt
	#
	pre="${UCOL}[$USER@$HOSTNAME]$CYAN($t)$GREEN$PWD"
	#
	# if the last command wasn't successful, then display the RC in $RED
	#
	[ $RET == 0 ]  || pre=${pre}${RED}[${RET}]
} 

Setup
export PROMPT_COMMAND=FPromptCmd

export PS1="${pre}_:${WHITE}"
